apiVersion: apps/v1
kind: Deployment
metadata:
  name: aditya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aditya
  template:
    metadata:
      labels:
        app: aditya
    spec:
      containers:
        - name: aditya
          image: cs162/workspace:latest
          tty: true
          ports:
            - containerPort: 22
          resources:
            limits:
              memory: 4Gi
              cpu: "4"
            requests:
              memory: 4Gi
              cpu: "1"
          volumeMounts:
            - name: aditya
              mountPath: /home/vagrant
      volumes:
        - name: aditya
          persistentVolumeClaim:
            claimName: aditya
