kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: swire-data
  namespace: bmt
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
