apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: outline-redis
  namespace: bmt
spec:
  encryptedData:
    password: AgAfrVoRkzNr/UWKWOz9is30RS3JNpvSrMzIfhUodAnvnvukRGvFR35zSNr+yHc3cH3bXNOeCCMNkMim7G7J275E/wnKeBhTWyM1wkYITosUoDs9m4fG41iHXls9AHf5zUxY1gtxjiKFhAueCUgm4Uaxn46nMf8JolJQEBSo1/QViVEzzKGWBtyVnnQz5R1SEKmfcsTvzjio8LshSz2rMg3aQyFxddVJWnJCCxoKAxCO07e83jj8hS95BX8duS9+loWNK6iWU5gawwl2oHyAIo9JBBA4eViUY22LhTWcA3MK4I9ABFZ/pq7uDyjg8d/hm/4DtpXuvIv9vPhL3PPMlcVB2VKv3NERL5JVXXX1qslLqD/klf0kPTkcDHbO8PMqOoCuwz6MK9L2SsV4FlJY/2N4Ztxo1beOogdgVDVQgHNY0waGSCo8xv2Og08+b2SyD5H0VvRnwGEQbASZScI0vMQljdvw3ZMIH1sqh2RmQFl+AmFa4MWKj8ajbhzFHAjJ7bNGfbyju2lkrXCP2Pyl2R3hVoxRdzQesLK710wkz4ycbtZbetswSVYL3wInsNtZHDv+SBhgSch6XfIkLCAdrOtJ0xUUo9vro4NaM4+P5JOyKAuSUTsXzAZdPv6+ogN+y7zdD3bcRAzA23s5b0N7615hDqaxMJvVH6rAr/yUrM7k/BZ91YZVsH2sNqXMsybIWsNWQh5lgK/vaUwu0I1v2/SnxxQYFkgQtU1b2vkJrnmI+w==
  template:
    metadata:
      creationTimestamp: null
      name: outline-redis
      namespace: bmt
    type: Opaque
