apiVersion: apps/v1
kind: Deployment
metadata:
  name: swire-client
  namespace: bmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swire-client
  template:
    metadata:
      labels:
        app: swire-client
    spec:
      containers:
        - name: swire-client
          image: ghcr.io/berkeleymt/swire-client:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "1Gi"
              cpu: "500m"
      imagePullSecrets:
        - name: ghcr-auth
